language: php
php:
  - '7.2'
before_script:
  - mkdir elements && mkdir elements/cache && mkdir elements/cache/dev && mkdir elements/cache/prod
  - composer install
script: phpunit --configuration phpunit.xml